apiVersion: sulla/v1
kind: Integration
id: postmark
name: Postmark
description: Send transactional emails with high deliverability and detailed analytics.
category: Marketing
version: 1.0.0
lastUpdated: 2026-02-28
developer: Wildbit
sort: 16
paid: true
beta: false
comingSoon: false
builtin: true
icon: postmark.svg
