apiVersion: sulla/v1
kind: Integration
id: square
name: Square
description: Process payments, manage inventory, and track sales data via Square.
category: Finance
version: 1.0.0
lastUpdated: 2026-02-28
developer: Block
sort: 5
paid: true
beta: false
comingSoon: false
builtin: true
icon: square.svg
