apiVersion: sulla/v1
kind: Integration
id: gladly
name: Gladly
description: Manage people-centered customer service across all channels.
category: Customer Support
version: 1.0.0
lastUpdated: 2026-02-28
developer: Gladly
sort: 13
paid: true
beta: false
comingSoon: false
builtin: true
icon: gladly.svg
