apiVersion: sulla/v1
kind: Integration
id: taiga
name: Taiga
description: Manage agile projects with user stories, tasks, and sprints.
category: Project Management
version: 1.0.0
lastUpdated: 2026-02-28
developer: Taiga
sort: 16
paid: false
beta: false
comingSoon: false
builtin: true
icon: taiga.svg
