apiVersion: sulla/v1
kind: Integration
id: vonage
name: Vonage
description: Send SMS, voice, and video communications via the Vonage APIs.
category: Communication
version: 1.0.0
lastUpdated: 2026-02-28
developer: Vonage
sort: 11
paid: true
beta: false
comingSoon: false
builtin: true
icon: vonage.svg
