apiVersion: sulla/v1
kind: Integration
id: calendly
name: Calendly
description: Manage scheduling links, events, and invitee data for automated booking.
category: Productivity
version: 1.0.0
lastUpdated: 2026-02-28
developer: Calendly
sort: 18
paid: true
beta: false
comingSoon: false
builtin: true
icon: calendly.svg
