apiVersion: sulla/v1
kind: Integration
id: uploadthing
name: UploadThing
description: Upload and manage files with a developer-friendly file hosting API.
category: File Storage
version: 1.0.0
lastUpdated: 2026-02-28
developer: UploadThing
sort: 13
paid: true
beta: false
comingSoon: false
builtin: true
icon: uploadthing.svg
