apiVersion: sulla/v1
kind: Integration
id: plausible
name: Plausible
description: Query lightweight, privacy-friendly website analytics data.
category: Analytics
version: 1.0.0
lastUpdated: 2026-02-28
developer: Plausible
sort: 6
paid: true
beta: false
comingSoon: false
builtin: true
icon: plausible.svg
