apiVersion: sulla/v1
kind: Integration
id: trello
name: Trello
description: Manage boards, lists, and cards. Automate Kanban-style project workflows.
category: Project Management
version: 1.0.0
lastUpdated: 2026-02-28
developer: Atlassian
sort: 4
paid: false
beta: false
comingSoon: false
builtin: true
icon: trello.svg
