apiVersion: sulla/v1
kind: Integration
id: turso
name: Turso
description: Manage edge-replicated SQLite databases powered by libSQL.
category: Database
version: 1.0.0
lastUpdated: 2026-02-28
developer: Turso
sort: 10
paid: true
beta: false
comingSoon: false
builtin: true
icon: turso.svg
