apiVersion: sulla/v1
kind: Integration
id: namely
name: Namely
description: Manage HR, payroll, benefits, and talent management for mid-size companies.
category: HR & Recruiting
version: 1.0.0
lastUpdated: 2026-02-28
developer: Namely
sort: 10
paid: true
beta: false
comingSoon: false
builtin: true
icon: namely.svg
