apiVersion: sulla/v1
kind: Integration
id: recurly
name: Recurly
description: Manage subscription billing, plans, invoices, and revenue recovery.
category: Finance
version: 1.0.0
lastUpdated: 2026-02-28
developer: Recurly
sort: 9
paid: true
beta: false
comingSoon: false
builtin: true
icon: recurly.svg
