apiVersion: sulla/v1
kind: Integration
id: framer
name: Framer
description: Manage interactive prototypes and publish responsive websites from designs.
category: Design
version: 1.0.0
lastUpdated: 2026-02-28
developer: Framer
sort: 7
paid: true
beta: false
comingSoon: false
builtin: true
icon: framer.svg
