apiVersion: sulla/v1
kind: Integration
id: salesloft
name: Salesloft
description: Manage cadences, track calls and emails, and automate sales engagement.
category: CRM & Sales
version: 1.0.0
lastUpdated: 2026-02-28
developer: Salesloft
sort: 11
paid: true
beta: false
comingSoon: false
builtin: true
icon: salesloft.svg
