apiVersion: sulla/v1
kind: Integration
id: oyster
name: Oyster
description: Hire, pay, and manage global employees and contractors compliantly.
category: HR & Recruiting
version: 1.0.0
lastUpdated: 2026-02-28
developer: Oyster
sort: 14
paid: true
beta: false
comingSoon: false
builtin: true
icon: oyster.svg
