apiVersion: sulla/v1
kind: Integration
id: plaid
name: Plaid
description: Connect bank accounts, retrieve transactions, and verify account balances.
category: Finance
version: 1.0.0
lastUpdated: 2026-02-28
developer: Plaid
sort: 8
paid: true
beta: false
comingSoon: false
builtin: true
icon: plaid.svg
