apiVersion: sulla/v1
kind: Integration
id: ramp
name: Ramp
description: Manage corporate cards, expenses, and spend management automation.
category: Finance
version: 1.0.0
lastUpdated: 2026-02-28
developer: Ramp
sort: 14
paid: true
beta: false
comingSoon: false
builtin: true
icon: ramp.svg
