apiVersion: sulla/v1
kind: Integration
id: clearbit
name: Clearbit
description: Enrich contacts and companies with firmographic and technographic data.
category: CRM & Sales
version: 1.0.0
lastUpdated: 2026-02-28
developer: HubSpot
sort: 16
paid: true
beta: false
comingSoon: false
builtin: true
icon: clearbit.svg
