apiVersion: sulla/v1
kind: Integration
id: google_analytics
name: Google Analytics
description: Query website traffic, user behavior, and conversion data from Google Analytics.
category: Analytics
version: 1.0.0
lastUpdated: 2026-02-28
developer: Google
sort: 1
paid: false
beta: false
comingSoon: false
builtin: true
icon: google_analytics.svg
