apiVersion: sulla/v1
kind: Integration
id: brex
name: Brex
description: Manage corporate cards, expenses, reimbursements, and budgets.
category: Finance
version: 1.0.0
lastUpdated: 2026-02-28
developer: Brex
sort: 7
paid: true
beta: false
comingSoon: false
builtin: true
icon: brex.svg
