apiVersion: sulla/v1
kind: Integration
id: jira
name: Jira
description: Create and manage issues, sprints, and boards. Automate Agile project tracking workflows.
category: Project Management
version: 1.0.0
lastUpdated: 2026-02-28
developer: Atlassian
sort: 1
paid: true
beta: false
comingSoon: false
builtin: true
icon: jira.svg
