apiVersion: sulla/v1
kind: Integration
id: sharepoint
name: SharePoint
description: Manage document libraries, lists, and sites in Microsoft SharePoint.
category: File Storage
version: 1.0.0
lastUpdated: 2026-02-28
developer: Microsoft
sort: 7
paid: true
beta: false
comingSoon: false
builtin: true
icon: sharepoint.svg
