apiVersion: sulla/v1
kind: Integration
id: sketch
name: Sketch
description: Access design files, artboards, and symbols. Export assets from Sketch Cloud.
category: Design
version: 1.0.0
lastUpdated: 2026-02-28
developer: Sketch B.V.
sort: 4
paid: true
beta: false
comingSoon: false
builtin: true
icon: sketch.svg
