apiVersion: sulla/v1
kind: Integration
id: linear
name: Linear
description: Manage issues, projects, and cycles. Streamline software development tracking.
category: Project Management
version: 1.0.0
lastUpdated: 2026-02-28
developer: Linear
sort: 2
paid: true
beta: false
comingSoon: false
builtin: true
icon: linear.svg
