apiVersion: sulla/v1
kind: Integration
id: fauna
name: Fauna
description: Query document-relational databases with distributed ACID transactions.
category: Database
version: 1.0.0
lastUpdated: 2026-02-28
developer: Fauna
sort: 11
paid: true
beta: false
comingSoon: false
builtin: true
icon: fauna.svg
