apiVersion: sulla/v1
kind: Integration
id: help_scout
name: Help Scout
description: Manage mailboxes, conversations, and customers. Automate email-based support.
category: Customer Support
version: 1.0.0
lastUpdated: 2026-02-28
developer: Help Scout
sort: 5
paid: true
beta: false
comingSoon: false
builtin: true
icon: help_scout.svg
