apiVersion: sulla/v1
kind: Integration
id: drift
name: Drift
description: Manage conversational marketing, chatbots, and meeting scheduling.
category: Customer Support
version: 1.0.0
lastUpdated: 2026-02-28
developer: Salesloft
sort: 12
paid: true
beta: false
comingSoon: false
builtin: true
icon: drift.svg
