apiVersion: sulla/v1
kind: Integration
id: terraform_cloud
name: Terraform Cloud
description: Manage workspaces, trigger runs, and automate infrastructure provisioning.
category: Developer Tools
version: 1.0.0
lastUpdated: 2026-02-28
developer: HashiCorp
sort: 13
paid: true
beta: false
comingSoon: false
builtin: true
icon: terraform_cloud.svg
