apiVersion: sulla/v1
kind: Integration
id: mastodon
name: Mastodon
description: Post toots, manage follows, and interact with the decentralized Fediverse.
category: Social Media
version: 1.0.0
lastUpdated: 2026-02-28
developer: Mastodon
sort: 12
paid: false
beta: false
comingSoon: false
builtin: true
icon: mastodon.svg
